name: 'IAxPresenceFootsteps'
version: '${project.version}'

main: 'ch.andre601.iaxpresencefootsteps.IAxPresenceFootsteps'

api-version: 1.18

softdepend:
- 'ItemsAdder'

libraries:
- org.json:json:20220320
- net.kyori:adventure-api:4.10.1
- net.kyori:adventure-text-minimessage:4.10.1
- net.kyori:adventure-platform-bukkit:4.1.0


commands: 
  pfcreate:
    aliases:
    - 'pfc'
    description: 'Creates the JSON file for the PresenceFootsteps mod.'
    usage: '/<command> [--override]'
    default: op
    permission: 'iaxpf.command.pfcreate'
  pfreload:
    aliases:
    - 'pfr'
    description: 'Reloads the plugin configuration.'
    usage: '/<command>'
    default: op
    permission: 'iaxpf.command.pfreload'