name: Bug Report
description: 'Please use this template if you found a bug or experience an issue with the plugin.'

body:
- type: markdown
  attributes:
    value: |-
      Thank you for reporting a bug.
      Make sure to fill out the issue form in its entirety and provide the requested information.
      
      Before submitting, make sure that you...
      
      - Use the latest version of the plugin.
      - Use the latest version of ItemsAdder.
      
      This place is not for requesting new features or general help with ItemsAdder!
- type: checkboxes
  attributes:
    label: I confirm that
    description: 'Please confirm that you made the below checks first.'
    options:
    - label: 'I use the latest version of IAxPresenceFootsteps (`/version IAxPresenceFootsteps`)'
      required: true
    - label: 'I use the latest version of ItemsAdder (`/version ItemsAdder`)'
      required: true
    - label: 'This issue also happens with only using ItemsAdder and this plugin.'
      required: true
- type: textarea
  attributes:
    label: Description
    placeholder: 'IAxPresenceFootsteps does...'
    description: |-
      What kind of issue do you encounter? Describe it in as much detail as possible.
      
      **Do not post errors here! Use the "Errors" Section below for those!**
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder: |-
      1. Do this
      2. ...
      3. Profit!
    description: 'Please provide steps to reproduce this issue **reliably**.'
  validations:
    required: true
- type: input
  attributes:
    label: Errors
    placeholder: 'https://paste.helpch.at/abcdef'
    description: |-
      Provide any errors you found in the console.
      You may do this by copying the error from the console (or from the `latest.log` file), open https://paste.helpch.at and paste it using <kbd>Ctrl</kbd>+<kbd>C</kbd>.
      Afterwards, save the paste using <kbd>Ctrl</kbd>+<kbd>S</kbd> and share the URL in the field below.
      
      You may leave this empty if no error is available.
- type: textarea
  attributes:
    label: Plugins used
    placeholder: 'Plugins (4): APlugin, AnotherPlugin, IAxPresenceFootsteps, ItemsAdder'
    description: 'Please provide the output of `/pl`'
- type: input
  attributes:
    label: Server logs
    placeholder: 'https://paste.helpch.at/abcdef'
    description: |-
      Provide the **complete** output of the `latest.log` file from your server.
      You may do this by copying the content of your `latest.log` file, open https://paste.helpch.at and paste it using <kbd>Ctrl</kbd>+<kbd>C</kbd>.
      Afterwards, save the paste using <kbd>Ctrl</kbd>+<kbd>S</kbd> and share the URL in the field below.
  validations:
    required: true






